### ISSUE TITLE
自分のWebcamでは動画のエンコード形式が対応していない

### ISSUE THREAD

**Issue by tzatter** [ymym3412/WindowsML-CoreML-MobileNet-demo#1]
こんにちは、素晴らしいサンプルをありがとうございます。Qiitaから来ました。

自分のwebカメラでは動画のエンコーディング形式のRGB24が残念ながら対応していませんでした。
対応しているのはMJPG,YUY2でした。これに書き換えて変更すれば動作しました。

カメラの動画のエンコーディングの対応状況を自動で判断して設定するにはどうすればいいのか調べた所、MediaCapture.FindAllVideoProfilesが動画のエンコーディングの対応している一覧を返すらしいのですが、何も返してくれません。自動で判断して設定する方法はないのでしょうか？

WebカメラはBuffaloのBSWHD06Mです
http://buffalo.jp/product/multimedia/web-camera/bswhd06m/

**Comment by ymym3412** [comment]
私が利用していたWebカメラが古く手動でSubtypeを指定してしまっていますが、最近のWebカメラ(Win10対応しているもの)であれば具体的にVideoEnodingPropertiesでSubTypeを指定しなくても動作します

```csharp
mediaCapture = new MediaCapture();
await mediaCapture.InitializeAsync(captureInitSettings);

//この部分をコメントアウトしても動く
//VideoEncodingProperties vp = new VideoEncodingProperties();
//vp.Height = 720;
//vp.Width = 1280;
//vp.Subtype = "RGB24";

//await mediaCapture.VideoDeviceController.SetMediaStreamPropertiesAsync(MediaStreamType.VideoPreview, vp);
capture.Source = mediaCapture;
```

もし使用しているWebカメラが対応しているエンコーディング(SubType)を自動で設定したいのであれば、 `MediaCapture.VideoDeviceController.GetAvailableMediaStreamProperties(MediaStreamType.VideoPreview)` で取得することも可能です

```csharp

mediaCapture = new MediaCapture();
await mediaCapture.InitializeAsync(captureInitSettings);

var properties = mediaCapture.VideoDeviceController.GetAvailableMediaStreamProperties(MediaStreamType.VideoPreview);
foreach (VideoEncodingProperties prop in properties)
{
    Debug.WriteLine(prop.Subtype);
    // e.g. YUY2
}
```

**Comment by tzatter** [comment]
お忙しいところ、お時間を割いていただきありがとうございます。
Subtypeを指定しなくても動作するのと、自動設定の仕方を詳しく教えてくださりありがとうございました。
